---
- name: Deploy Peer Match
  hosts: all
  become: true
  vars_files:
    - group_vars/all.yml
    - secrets.yml

  roles:
    - { role: docker, when: "'web' in group_names" }
    - { role: postgresql, when: "'db' in group_names" }
    - { role: app, when: "'web' in group_names" }
