services:
  db:
    image: postgres:18
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/18/data/
    networks:
      - main
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  api:
    build: backend/
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    depends_on:
      db:
        condition: service_healthy
    networks:
      - main

#  frontend: TODO: ФРОНТЕНДЕРЫ ОТРЕДАКТИРУЙТЕ
#    build: frontend/
#    ports:
#      - "5173:5173"
#    environment:
#      - NODE_ENV=production
#      - REACT_APP_API_URL=/api/
#    depends_on:
#      - api
#    networks:
#      main:
#    restart: unless-stopped

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      #- frontend
      - api
    networks:
      - main

  redis:
    image: redis:latest
    container_name: redis-cache
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    volumes:
      - redis_data:/data
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}

volumes:
  postgres_data:
  redis_data:
    driver: local

networks:
  main:
    driver: bridge