include:
  - ./docker-compose.base.yml

services:
  api:
    image: ${CI_REGISTRY_IMAGE}/backend:${CI_COMMIT_SHA}
    env_file: ../../.env
    depends_on:
      s3-storage:
        condition: service_healthy
      cache:
        condition: service_healthy
    networks:
      - main
  
  nginx:
    build: ../../nginx
    ports:
      - "80:80"
    depends_on:
      #- frontend
      - api
    networks:
      - main