build_backend_image:
  image:
    name: moby/buildkit:rootless
    entrypoint: [""]
  stage: build
  variables:
    BUILDKITD_FLAGS: --oci-worker-no-process-sandbox
    IMAGE_TAG: $CI_COMMIT_SHA
    IMAGE_NAME: $CI_REGISTRY_IMAGE/backend:$IMAGE_TAG
  services:
    - name: moby/buildkit:0.12.5
      alias: buildkitd
      command: ["--addr", "tcp://0.0.0.0:1234"]
  before_script:
    - apk add docker-cli
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - |
      buildctl-daemonless.sh build \
        --frontend dockerfile.v0 \
        --local context=backend \
        --local dockerfile=backend \
        --opt target=prod \
        --output type=image,name=$IMAGE_NAME,push=true \
        --opt platform=linux/amd64,linux/arm64 \
        --import-cache type=registry,ref=$IMAGE_NAME \
        --export-cache type=registry,ref=$IMAGE_NAME,mode=max
