.ruff_lint_base:
  stage: lint
  image: registry.gitlab.com/pipeline-components/ruff:latest
  before_script:
    - cd backend
  only:
    - main

ruff_lint:
  extends: .ruff_lint_base
  script:
    - ruff check --output-format=gitlab .

ruff_format:
  extends: .ruff_lint_base
  script:
    - ruff format --check --verbose .
